name: Run tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    # ⚠️ Genera índice dummy SOLO para CI
    - name: Build tiny FAISS index for CI
      run: |
        python - <<'PY'
        import faiss, numpy as np, pickle
        dim = 3
        index = faiss.IndexFlatIP(dim)
        index.add(np.zeros((1, dim), dtype='float32'))
        faiss.write_index(index, "vector_index.faiss")
        with open("metadata.pkl", "wb") as f:
            pickle.dump({0: {"label": "dummy", "path": "dummy"}}, f)
        PY

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install httpx pytest pytest-mock pytest-cov

    - name: Run tests
      run: |
        pytest -v
